services:
  moodle:
    image: bitnami/moodle:4.4
    container_name: moodle_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MOODLE_DATABASE_TYPE=mariadb
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodlepassword
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin123
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_SITE_NAME=My Moodle Site
      - MOODLE_SITE_URL=http://localhost:8080
      - MOODLE_SKIP_INSTALL=no
      - MOODLE_SKIP_BOOTSTRAP=no
      - APACHE_HTTP_PORT_NUMBER=8080
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_MAX_FILESIZE=100M
      - PHP_POST_MAX_SIZE=100M
      - PHP_MAX_EXECUTION_TIME=300
    volumes:
      - moodle_data:/bitnami/moodle
    depends_on:
      - mariadb
    networks:
      - moodle_network

  mariadb:
    image: bitnami/mariadb:10.11
    container_name: moodle_db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=moodlepassword
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - moodle_network

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: moodle_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=moodle
      - PMA_PASSWORD=moodlepassword
    depends_on:
      - mariadb
    networks:
      - moodle_network

volumes:
  moodle_data:
    driver: local
  mariadb_data:
    driver: local

networks:
  moodle_network:
    driver: bridge